#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# BATHOS  scripts/to-codex.sh  —  Claude Code 자산 → OpenAI Codex CLI 변환(스캐폴드)
#
#   .claude/commands/*.md      → <dest>/prompts/*.md          (/prompts:<name>)
#   .claude/agents/_base/*.md  → <dest>/agents/<slug>.toml    (서브에이전트 정의)
#
# 이 스크립트는 **기계적 80%** 만 변환한다. 다음은 수동 적응(docs/codex-adapter-kr.md):
#   - 훅 기반 게이트(TaskCompleted→PreToolUse exit-2), SessionEnd 종료 루틴(→Stop)
#   - MCP 등록, 모델 프로바이더(responses-only), 팀 스폰 로직(Task→Codex 서브에이전트)
#
# 사용:
#   bash scripts/to-codex.sh                 # dry-run(미리보기)
#   bash scripts/to-codex.sh --write         # 실제 생성(기본 dest = ./.codex-out)
#   bash scripts/to-codex.sh --write --dest ~/.codex   # 위치 지정
#
# 철칙: 날조 금지. model 은 원본(claude-*)을 주석으로 보존하고, Codex 모델은
#       사용자가 지정하도록 비워 둔다(임의 모델명 삽입 금지).
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ="$(cd "$SCRIPT_DIR/.." && pwd)"
WRITE=0
DEST="$PROJ/.codex-out"

while [ $# -gt 0 ]; do
  case "$1" in
    --write) WRITE=1 ;;
    --dest) shift; DEST="$1" ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "알 수 없는 인자: $1" >&2; exit 2 ;;
  esac
  shift
done

CMD_SRC="$PROJ/.claude/commands"
AGT_SRC="$PROJ/.claude/agents/_base"
PROMPT_DST="$DEST/prompts"
AGENT_DST="$DEST/agents"

say(){ printf '%s\n' "$*"; }
[ "$WRITE" = "1" ] && say "== 실제 생성 → $DEST ==" || say "== DRY-RUN(미리보기) — 실제 생성하려면 --write =="

# frontmatter 값 추출(첫 --- 블록에서 key: value, 인라인 주석 제거)
fm_val(){ # $1=file $2=key
  awk -v k="$2" '
    NR==1 && $0 ~ /^---[[:space:]]*$/ {inf=1; next}
    inf && $0 ~ /^---[[:space:]]*$/ {exit}
    inf {
      line=$0; sub(/#.*/,"",line)                       # 인라인 주석 제거
      if (line ~ "^[[:space:]]*" k "[[:space:]]*:") {
        sub("^[[:space:]]*" k "[[:space:]]*:[[:space:]]*","",line)
        gsub(/^[[:space:]]+|[[:space:]]+$/,"",line)
        print line; exit
      }
    }' "$1"
}
# 본문(두 번째 --- 이후) 추출
body_after_fm(){ awk 'p{print} /^---[[:space:]]*$/{c++; if(c==2)p=1}' "$1"; }

# ---- 1) 커맨드 → prompts ----
ncmd=0
if [ -d "$CMD_SRC" ]; then
  [ "$WRITE" = "1" ] && mkdir -p "$PROMPT_DST"
  for f in "$CMD_SRC"/*.md; do
    [ -e "$f" ] || continue
    base="$(basename "$f")"; ncmd=$((ncmd+1))
    if [ "$WRITE" = "1" ]; then
      cp "$f" "$PROMPT_DST/$base"      # description/argument-hint front matter는 Codex도 인식
    else
      say "  [prompt] $base  (/prompts:${base%.md})"
    fi
  done
fi

# ---- 2) 에이전트 → agents/*.toml ----
nagt=0
if [ -d "$AGT_SRC" ]; then
  [ "$WRITE" = "1" ] && mkdir -p "$AGENT_DST"
  for f in "$AGT_SRC"/*.md; do
    [ -e "$f" ] || continue
    slug="$(fm_val "$f" slug)"; [ -z "$slug" ] && slug="$(fm_val "$f" name)"
    [ -z "$slug" ] && slug="$(basename "${f%.md}")"
    model="$(fm_val "$f" model)"
    spawnable="$(fm_val "$f" spawnable)"
    # description = 본문 첫 비어있지 않은 non-heading 줄
    desc="$(body_after_fm "$f" | sed '/^[[:space:]]*$/d; /^#/d' | head -1)"
    [ -z "$desc" ] && desc="BATHOS role $slug"
    nagt=$((nagt+1))

    if [ "$WRITE" = "1" ]; then
      {
        printf '# generated by scripts/to-codex.sh from %s\n' "$(basename "$f")"
        printf '# source model: %s   (Codex 모델은 아래 model 을 직접 지정하세요 — 임의 삽입 금지)\n' "${model:-미지정}"
        printf '# spawnable: %s\n\n' "${spawnable:-미지정}"
        printf 'name = "%s"\n' "$slug"
        printf 'description = "%s"\n' "$(printf '%s' "$desc" | sed 's/"/\\"/g')"
        printf '# model = "gpt-5-codex"   # TODO: 사용자 지정\n'
        printf '# model_reasoning_effort = "high"\n\n'
        printf 'developer_instructions = """\n'
        body_after_fm "$f" | sed 's/"""/\\"\\"\\"/g'
        printf '\n"""\n'
      } > "$AGENT_DST/$slug.toml"
    else
      say "  [agent]  $slug.toml  (src model: ${model:-미지정}, spawnable: ${spawnable:-미지정})"
    fi
  done
fi

say ""
say "요약: 커맨드 $ncmd 개 → prompts, 에이전트 $nagt 개 → agents/*.toml"
if [ "$WRITE" = "1" ]; then
  say "생성 위치: $DEST"
  say "다음(수동): 훅 게이트 재설계·SessionEnd 근사·MCP·모델 프로바이더 — docs/codex-adapter-kr.md §3~4"
else
  say "실제 생성: bash scripts/to-codex.sh --write [--dest <경로>]"
fi
